# Railway Config as Code
# Docs: https://docs.railway.com/reference/config-as-code

[build]
# Use Dockerfile (Railway will auto-detect and prioritize Dockerfile)
builder = "DOCKERFILE"

[deploy]
# Let Dockerfile CMD handle startup with proper shell expansion
# startCommand = "uvicorn api_service:app --host 0.0.0.0 --port $PORT"
# Healthcheck
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"

